export const AgentLineEvent = {
  AgentCreated: 'agent.created',
  AgentUpdated: 'agent.updated',
  AgentDisabled: 'agent.disabled',
  NumberProvisioned: 'agent.number.provisioned',
  NumberImported: 'agent.number.imported',
  NumberAttached: 'agent.number.attached',
  NumberDetached: 'agent.number.detached',
  NumberReleased: 'agent.number.released',
  NumberFailed: 'agent.number.failed',
  MessageSent: 'agent.message.sent',
  MessageReceived: 'agent.message.received',
  MessageDeliveryUpdated: 'agent.message.delivery_updated',
  CallStarted: 'agent.call.started',
  CallStatusUpdated: 'agent.call.status_updated',
  CallTranscriptUpdated: 'agent.call.transcript_updated',
  CallCompleted: 'agent.call.completed',
  CallFailed: 'agent.call.failed',
  CallEnded: 'agent.call.ended',
  CallTransferred: 'agent.call.transferred',
  ConversationCreated: 'agent.conversation.created',
  ConversationUpdated: 'agent.conversation.updated',
  ContactCreated: 'agent.contact.created',
  ContactUpdated: 'agent.contact.updated',
  UsageRecorded: 'agent.usage.recorded',
  UsageFinalized: 'agent.usage.finalized',
  UsageVoided: 'agent.usage.voided',
  WebhookTest: 'webhook.test',
} as const;

export const AgentLineEventPattern = {
  All: '*',
  Agents: 'agent.*',
  Calls: 'agent.call.*',
  Messages: 'agent.message.*',
  Numbers: 'agent.number.*',
  Conversations: 'agent.conversation.*',
  Contacts: 'agent.contact.*',
  Usage: 'agent.usage.*',
} as const;

export const AuditAction = {
  WorkspaceCreated: 'workspace.created',
  WorkspaceUpdated: 'workspace.updated',
  MemberRoleUpdated: 'member.role_updated',
  MemberRemoved: 'member.removed',
  InviteCreated: 'invite.created',
  InviteRevoked: 'invite.revoked',
  InviteResent: 'invite.resent',
  InviteAccepted: 'invite.accepted',
  InviteExpired: 'invite.expired',
  ApiKeyCreated: 'api_key.created',
  ApiKeyUpdated: 'api_key.updated',
  ApiKeyRevoked: 'api_key.revoked',
  ApiKeyRotated: 'api_key.rotated',
  BillingControlsUpdated: 'billing.controls_updated',
  BillingCreditApplied: 'billing.credit_applied',
  BillingCheckoutExpired: 'billing.checkout_expired',
  BillingSubscriptionSynced: 'billing.subscription_synced',
  BillingInvoicePaid: 'billing.invoice_paid',
  BillingInvoicePaymentFailed: 'billing.invoice_payment_failed',
  CallCreated: 'call.created',
  CallFailed: 'call.failed',
  CallEnded: 'call.ended',
  CallTransferred: 'call.transferred',
  NumberProvisioned: 'number.provisioned',
  NumberImported: 'number.imported',
  NumberAttached: 'number.attached',
  NumberDetached: 'number.detached',
  NumberReleased: 'number.released',
  WebhookEndpointCreated: 'webhook_endpoint.created',
  WebhookEndpointUpdated: 'webhook_endpoint.updated',
  WebhookEndpointDisabled: 'webhook_endpoint.disabled',
  WebhookDeliveryTested: 'webhook_delivery.tested',
  WebhookDeliveryRetried: 'webhook_delivery.retried',
  WebhookDeliveryExhausted: 'webhook_delivery.exhausted',
} as const;

export const EventResourceType = {
  Agent: 'agent',
  ApiKey: 'api_key',
  BillingBalance: 'billing_balance',
  BillingSubscription: 'billing_subscription',
  BillingTransaction: 'billing_transaction',
  Call: 'call',
  Contact: 'contact',
  Conversation: 'conversation',
  Message: 'message',
  PhoneNumber: 'phone_number',
  UsageEvent: 'usage_event',
  WebhookEndpoint: 'webhook_endpoint',
  WebhookDelivery: 'webhook_delivery',
  Workspace: 'workspace',
  WorkspaceInvite: 'workspace_invite',
  WorkspaceMember: 'workspace_member',
} as const;
