export const AgentLineEvent = {
  AgentCreated: 'agent.created',
  AgentUpdated: 'agent.updated',
  AgentDisabled: 'agent.disabled',
  NumberProvisioned: 'agent.number.provisioned',
  NumberImported: 'agent.number.imported',
  NumberAttached: 'agent.number.attached',
  NumberDetached: 'agent.number.detached',
  NumberReleased: 'agent.number.released',
  NumberFailed: 'agent.number.failed',
  MessageSent: 'agent.message.sent',
  MessageReceived: 'agent.message.received',
  MessageDeliveryUpdated: 'agent.message.delivery_updated',
  CallStarted: 'agent.call.started',
  CallStatusUpdated: 'agent.call.status_updated',
  CallTranscriptUpdated: 'agent.call.transcript_updated',
  CallCompleted: 'agent.call.completed',
  CallFailed: 'agent.call.failed',
  CallEnded: 'agent.call.ended',
  CallTransferred: 'agent.call.transferred',
  ConversationCreated: 'agent.conversation.created',
  ConversationUpdated: 'agent.conversation.updated',
  ContactCreated: 'agent.contact.created',
  ContactUpdated: 'agent.contact.updated',
  UsageRecorded: 'agent.usage.recorded',
  UsageFinalized: 'agent.usage.finalized',
  UsageVoided: 'agent.usage.voided',
  WebhookTest: 'webhook.test',
} as const;

export const AgentLineEventPattern = {
  All: '*',
  Agents: 'agent.*',
  Calls: 'agent.call.*',
  Messages: 'agent.message.*',
  Numbers: 'agent.number.*',
  Conversations: 'agent.conversation.*',
  Contacts: 'agent.contact.*',
  Usage: 'agent.usage.*',
} as const;

export const AuditAction = {
  CallCreated: 'call.created',
  CallFailed: 'call.failed',
  CallEnded: 'call.ended',
  CallTransferred: 'call.transferred',
  NumberProvisioned: 'number.provisioned',
  NumberImported: 'number.imported',
  NumberAttached: 'number.attached',
  NumberDetached: 'number.detached',
  NumberReleased: 'number.released',
  WebhookEndpointCreated: 'webhook_endpoint.created',
  WebhookEndpointUpdated: 'webhook_endpoint.updated',
  WebhookEndpointDisabled: 'webhook_endpoint.disabled',
  WebhookDeliveryTested: 'webhook_delivery.tested',
  WebhookDeliveryRetried: 'webhook_delivery.retried',
  WebhookDeliveryExhausted: 'webhook_delivery.exhausted',
} as const;

export const EventResourceType = {
  Call: 'call',
  Message: 'message',
  PhoneNumber: 'phone_number',
  WebhookEndpoint: 'webhook_endpoint',
  WebhookDelivery: 'webhook_delivery',
} as const;
